### ISSUE TITLE
So many many bugs in current and next move win detection (bc you don't check the teams)

### ISSUE THREAD

**Issue by JeremySeq** [Krazy0range/super-ttt#2]
![image](https://github.com/user-attachments/assets/a472f04c-0310-4d72-b909-8535add8a233)
The next move does not, in fact, win a mini board.

![Screenshot 2024-11-11 180211](https://github.com/user-attachments/assets/0ff972d8-40b8-463c-acac-a2d167d7d0f5)
This move does not actually win a mini board.

**Comment by krazyorange13** [comment]
install the right fcking [font](https://github.com/ryanoasis/nerd-fonts/releases/download/v3.2.1/3270.zip)
but yeah i do need to do that
trying to code with a fever go brrr

**Comment by krazyorange13** [comment]
added player information for next moves. i'm going to keep all the hints though (_for now_) because its still useful for lookaheads.
